#!/bin/bash

envs=()
args=()

while [[ ${#} -gt 0 ]]; do
    arg=${1}; case ${arg} in
        -m | --model ) shift; model=${1}     ;;
        -o | --odir  ) shift; odir=${1}      ;;
        -e | --env   ) shift; envs+=("${1}") ;;
             --multi ) shift; multi=${1}     ;;
         *           )        args+=("${1}") ;;
    esac; shift
done

echo

for keyval in ${envs[@]}; do
    key=${keyval%%=*}
    val=${keyval#*=}

    echo "FMWORK EXP ${keyval}"

    if [[ ${val} == __UNSET__ ]]; then unset  ${key}
    else                               export ${key}=${val}
    fi
done

# multi-runs is off; usual / single run
# -------------------------------------

if [[ -z "${multi}" ]]; then

cmd="
vllm bench serve
    --model ${model}
    ${args[*]}
"

# Store start time in UTC
echo "client_time_start:$(date -u "+%s.%N")"

echo
env | sort | sed 's/^/FMWORK ENV /'
echo
echo ${cmd}
echo
eval ${cmd}

# Store end time in UTC
echo "client_time_end:$(date -u "+%s.%N")"

# multi-runs enabled!
# -------------------

else

instance=0

for combo in ${multi//,/ }; do

ii=$(echo ${combo} | cut -d / -f 1)
oo=$(echo ${combo} | cut -d / -f 2)
bb=$(echo ${combo} | cut -d / -f 3)
rr=$(echo ${combo} | cut -d / -f 4)

{

cmd="
vllm bench serve
    --model ${model}
    ${args[*]}
    --dataset-name random
    --random-input-len  ${ii}
    --random-output-len ${oo}
    --max-concurrency   ${bb}
    --num-prompts       ${rr}
"

echo "$(date) -- starting ${instance}"

# Store start time in UTC
echo "client_time_start:$(date -u "+%s.%N")"

echo        &>> ${odir}/client.log.${instance}
echo ${cmd} &>> ${odir}/client.log.${instance}
echo        &>> ${odir}/client.log.${instance}
eval ${cmd} &>> ${odir}/client.log.${instance}

# Store end time in UTC
echo "client_time_end:$(date -u "+%s.%N")"

echo "$(date) -- finished ${instance}"

} &

instance=$(( instance + 1 ))

done

echo "$(date) -- clients started; waiting for completion ..."

wait

echo "$(date) -- all done!"

sleep 4

fi

