#!/bin/bash

envs=()
args=()

while [[ ${#} -gt 0 ]]; do
    arg=${1}; case ${arg} in
        -m | --model ) shift; model=${1}     ;;
        -e | --env   ) shift; envs+=("${1}") ;;
         *           )        args+=("${1}") ;;
    esac; shift
done

echo

for keyval in ${envs[@]}; do
    key=${keyval%%=*}
    val=${keyval#*=}

    echo "FMWORK EXP ${keyval}"

    if [[ ${val} == __UNSET__ ]]; then unset  ${key}
    else                               export ${key}=${val}
    fi
done

cmd="
vllm bench serve
    --model ${model}
    ${args[*]}
"

echo
env | sort | sed 's/^/FMWORK ENV /'
echo
echo ${cmd}
echo
eval ${cmd}

