#!/usr/bin/env python3

import argparse
import json
import os
import sys
import traceback

class fmwork:
    class Exception(Exception):
        pass

def main():

    parser = argparse.ArgumentParser()
    parser.add = parser.add_argument
    parser.add('--path',         type=str, required=True)
    parser.add('--precision',    type=str, default='fp16')
    parser.add('--metadata_id',  type=str)
    args = parser.parse_args()

    if os.path.isdir(args.path):
        if os.path.exists(os.path.join(args.path, 'server.log')):
            return process_server(args)

    return process_direct(args)

def process_direct(args):

    if os.path.isdir(args.path):
        log_driver = os.path.join(args.path, 'driver.log')
    else:
        log_driver = args.path

    warmup     = None
    batch_mode = 'static'

    if not os.path.exists(log_driver):
        raise fmwork.Exception(
            f'Could not find {log_driver}.')

    opts = []
    hits = []

    for line in open(log_driver, errors='ignore'):
        if warmup is None:
            if 'init engine (profile, create kv cache, warmup model) took' in line:
                warmup = float(line.split('took ')[1].split(' seconds')[0])

        if line.startswith('FMWORK EXP'):

            split = line.strip().split(' ')
            opt = '--env ' + ' '.join(split[2:])
            opts.append(opt)

            if 'VLLM_SPYRE_USE_CB' in line:
                value = line.strip().split('=')[-1]
                if value == '1':
                    batch_mode = 'continuous'

        if line.startswith('FMWORK ARG'):

            opts.append(line.strip()[11:])

        if line.startswith('FMWORK SETUP'):

            setup = float(line.strip().split(' ')[-1])

        if line.startswith('FMWORK GEN'):

            split = line.strip().split(' ')

            time_start  =       split[2]
            time_end    =       split[3]
            model_name  =       split[4]
            input_size  =   int(split[5])
            output_size =   int(split[6])
            batch_size  =   int(split[7])
            tp_size     =   int(split[8])
            ttft_r      = float(split[9])
            inf_r       = float(split[10])
            inf         = float(split[11])
            gen         = float(split[12])
            ttft        = float(split[13])
            itl         = float(split[14])
            thp         = float(split[15])

            hits.append({
                'timestamp'     : time_start,
                'metadata_id'   : args.metadata_id,
                'engine'        : 'fmwork/infer/vllm',
                'model'         : model_name,
                'precision'     : args.precision,
                'input'         : input_size,
                'output'        : output_size,
                'batch'         : batch_size,
                'tp'            : tp_size,
                'opts'          : opts,
                'warmup'        : round(warmup, 3) if warmup is not None else None,
                'setup'         : setup,
                'ttft'          : ttft,
                'itl'           : itl,
                'thp'           : thp,
                'mode'          : 'direct',
                'batch_mode'    : batch_mode,
                'range_ratio'   : 0.0,
            })

    print(json.dumps(hits, indent=4))

def process_server(args):

    log_runner  = os.path.join(args.path, 'runner.log')
    cmd_server  = os.path.join(args.path, 'server.cmd')
    log_server  = os.path.join(args.path, 'server.log')
    cmd_client  = os.path.join(args.path, 'client.cmd')
    log_client  = os.path.join(args.path, 'client.log')
    log_metrics = os.path.join(args.path, 'metrics.log')

    for path in [
        cmd_server, log_server,
        cmd_client, log_client,
        log_metrics,
    ]:
        if not os.path.exists(path):
            raise fmwork.Exception(
                f'Could not find {path}.')

    opts = []

    # get model timestamps from runner log

    for line in open(log_runner):

        if line.startswith('model_name'):

            model_name = line.strip().split(' ')[-1]

        if line.startswith('time_start '):

            time_start = line.strip().split(' ')[-1]

        if line.startswith('time_end' ):

            time_end   = line.strip().split(' ')[-1]

    # get opts from server command and client command

    line = open(cmd_server).read().strip()
    for s in line.split('--')[1:]:
        opts.append('[server] --' + s.strip())

    line = open(cmd_client).read().strip()
    for s in line.split('--')[1:]:
        opts.append('[client] --' + s.strip())

    # read environment variables looking for meaningful information

    batch_mode = 'static'

    for line in open(log_server):
        if line.startswith('FMWORK EXP'):
            if 'VLLM_SPYRE_USE_CB' in line:
                value = line.strip().split('=')[-1]
                if value == '1':
                    batch_mode = 'continuous'

    # read parameters from opts

    input_size  = None
    output_size = None
    batch_size  = None
    tp_size     = None
    range_ratio = 0.0

    for opt in opts:
        split = opt.split(' ')
        cos   = split[0]
        key   = split[1]
        val   = ' '.join(split[2:])

        if cos == '[server]':
            if key == '--tensor-parallel-size': tp_size     =   int(val)
            if key == '--max-num-seqs':         batch_size  =   int(val)
        if cos == '[client]':
            if key == '--random-input-len':     input_size  =   int(val)
            if key == '--random-output-len':    output_size =   int(val)
            if key == '--random-range-ratio':   range_ratio = float(val)

    # process metrics

    for line in open(log_client):

        if line.startswith('Successful requests'):
            requests_ok  = int(line.strip().split(' ')[-1])

        if line.startswith('Total input tokens'):
            total_input  = int(line.strip().split(' ')[-1])

        if line.startswith('Total generated tokens'):
            total_output = int(line.strip().split(' ')[-1])

        if line.startswith('Benchmark duration'):
            total_time   = float(line.strip().split(' ')[-1])

        if line.startswith('Median TTFT (ms)'):
            ttft = float(line.strip().split(' ')[-1])

        if line.startswith('Median ITL (ms)'):
            itl  = float(line.strip().split(' ')[-1])

        if line.startswith('Output token throughput (tok/s)'):
            thp  = float(line.strip().split(' ')[-1])

    # for line in open(log_metrics):
    #
    #     if line.startswith('vllm:request_prefill_time_seconds_count'):
    #         reps = int(line.strip().split(' ')[-1].split('.')[0])
    #
    #     if line.startswith('vllm:request_prefill_time_seconds_sum'):
    #         prefill_sum = float(line.strip().split(' ')[-1])
    #
    # ttft = prefill_sum / reps + ( itl / 1000.0 )
    #
    # thp  = \
    #     ( batch_size * ( output_size - 1 ) ) / \
    #     ( output_size * ( itl / 1000.0 ) )

    # if shapes could not be read, might be using different dataset
    # read values from output instead

    if not input_size:  input_size  = int ( total_input  / requests_ok )
    if not output_size: output_size = int ( total_output / requests_ok )

    hits = [{
        'timestamp'     : time_start,
        'metadata_id'   : args.metadata_id,
        'engine'        : 'fmwork/infer/vllm',
        'model'         : model_name,
        'precision'     : args.precision,
        'input'         : input_size,
        'output'        : output_size,
        'batch'         : batch_size,
        'tp'            : tp_size,
        'opts'          : opts,
        'warmup'        : None,
        'setup'         : None,
        'ttft'          : round(ttft, 3),
        'itl'           : round(itl,  1),
        'thp'           : round(thp,  1),
        'mode'          : 'server',
        'batch_mode'    : batch_mode,
        'range_ratio'   : range_ratio,
    }]

    print(json.dumps(hits, indent=4))

if __name__ == '__main__':
    try:
        main(); sys.exit(0)
    except fmwork.Exception as e:
        print(e); sys.exit(1)
    except KeyboardInterrupt:
        print('Interrupted.'); sys.exit(2+128)
    except Exception:
        traceback.print_exc(); sys.exit(3)
