#!/usr/bin/env python3

import argparse
import json
import os

def main():

    parser = argparse.ArgumentParser()
    parser.add = parser.add_argument
    parser.add('--path',        type=str, required=True)
    parser.add('--metadata_id', type=str, required=True)
    args = parser.parse_args()

    opts = []
    hits = []

    for line in open(args.path):

        if line.startswith('FMWORK ARG'):

            opts.append(line.strip()[11:])

        if line.startswith('FMWORK RES'):

            split = line.strip().split(' ')

            time_start  =       split[2]
            time_end    =       split[3]
            model_name  =       split[4]
            model_class =       split[5]
            input_size  =   int(split[6])
            batch_size  =   int(split[7])
            latency     = float(split[8])
            throughput  = float(split[9])

            hits.append({
                'timestamp'     : time_start,
                'metadata_id'   : args.metadata_id,
                'engine'        : 'fmwork/embed/tf',
                'model'         : model_name,
                'precision'     : None,
                'input'         : input_size,
                'output'        : 1,
                'batch'         : batch_size,
                'tp'            : 1,
                'opts'          : opts,
                'warmup'        : None,
                'setup'         : None,
                'ttft'          : None,
                'itl'           : latency,
                'thp'           : throughput,
            })

    print(json.dumps(hits, indent=4))

if __name__ == '__main__':
    main()

